name: flutter_rocketchat
description: A new Flutter project.
version: 0.0.2
homepage: https://github.com/dev-kasibhatla/flutter_rocketchat

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  cookie_jar: ^4.0.8
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  hive: ^2.2.3
  web_socket_client: ^0.1.0
  dio_cookie_manager: ^3.1.1
  path_provider: ^2.1.1
  web_socket_channel: ^2.4.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: